language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="Adafruit IO Arduino Library"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - cd $HOME/arduino_ide/libraries/
   - wget https://github.com/adafruit/WiFiNINA/archive/master.zip && unzip master.zip
   - mv WiFiNINA-master/ WiFiNINA && rm master.zip
   - cd /home/travis/build/adafruit/Adafruit_IO_Arduino

install:
    - arduino --install-library "Adafruit IO Arduino","Adafruit MQTT Library","ArduinoHttpClient"
    - arduino --install-library "Adafruit Unified Sensor","Adafruit NeoPixel","DHT sensor library", "Ethernet"

script:
    - build_platform m4wifi
    - build_platform esp8266
